"""auto-vote

Revision ID: 939ffe4ef1c0
Revises: cf87b81498cd
Create Date: 2021-12-02 10:15:22.374913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.schema import Column


# revision identifiers, used by Alembic.
revision = '939ffe4ef1c0'
down_revision = 'cf87b81498cd'
branch_labels = None
depends_on = None


def upgrade():
    # op.add_column('posts',Column('owner_id',sa.Integer,nullable=False))
    # op.create_foreign_key('post_user_fk',source_table="posts",referent_table="users",
    # local_cols=['owner_id'],remote_cols=['id'], ondelete="CASCADE")

    # op.add_column('posts',sa.Column('published',sa.Boolean(),nullable=False,server_default=True))
    # op.add_column('posts',sa.Column('created_at',sa.TIMESTAMP(timezone=True),nullable=False,server_default=sa.text('Now()')))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # op.drop_column('posts','owner_id')
    # op.drop_column('posts','published')
    # op.drop_column('posts','created_at')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
